# Generated by Django 3.1.14 on 2022-07-12 15:57

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
